### ISSUE TITLE
Ganymed outdated

### ISSUE THREAD

**Issue by m13slash9** [davidfreedman/matlab-ssh2#4]
It looks like recent changes in ssh encryption (e.g., if the server is running the default current Ubuntu), ganymed cannot handle the ssh connection anymore.

The error comes up during establishing ssh connection in ssh2_main, line 61 with
`Java exception occurred:`
`java.io.IOException: Key exchange was not finished, connection is closed.`

	at ch.ethz.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:76)

	at ch.ethz.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:169)

	at ch.ethz.ssh2.Connection.connect(Connection.java:759)

	at ch.ethz.ssh2.Connection.connect(Connection.java:628)

`Caused by: java.io.IOException: Cannot negotiate, proposals do not match.`

	at ch.ethz.ssh2.transport.ClientKexManager.handleMessage(ClientKexManager.java:123)

	at ch.ethz.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:572)

	at ch.ethz.ssh2.transport.TransportManager$1.run(TransportManager.java:261)

Upgrading to [ganymed-ssh2-263](https://github.com/SoftwareAG/ganymed-ssh-2/releases/tag/ganymed-ssh2-263) doesn't seem to help either.

**Comment by juc023** [comment]
Hi, have you solved this issue?

**Comment by m13slash9** [comment]
I was only able to solve it by modifying server-side `/etc/ssh/sshd_config` file by adding

`KexAlgorithms diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1`
`HostKeyAlgorithms ssh-rsa,ssh-dss`
`PubkeyAcceptedKeyTypes +ssh-rsa`

**Comment by SchapplM** [comment]
I was not able to solve this because my server is maintained by someone else in my organization and supporting these algorithms is not possible due to security issues.
I had to switch to using the system command and call ssh/scp from there. I implemented this in [a fork](https://github.com/SchapplM/matlab-ssh-via-system) of this repository, so the interfaces stay the same, in case this workaround is useful for someone.

**Comment by m13slash9** [comment]
> I was not able to solve this because my server is maintained by someone else in my organization and supporting these algorithms is not possible due to security issues. I had to switch to using the system command and call ssh/scp from there. I implemented this in [a fork](https://github.com/SchapplM/matlab-ssh-via-system) of this repository, so the interfaces stay the same, in case this workaround is useful for someone.

Oh, nice! I was trying to do the same with native `ssh` and `scp` for Windows, but was not successful.

**Comment by bartkrekelberg** [comment]
I also ran into this problem and implemented a version that uses OpenSSH.  

On Windows, it can use the WSL Linux backend, which allows a single connection to be reused (much like the deprecated Ganymed implementation did). This speeds up communication with a remote server. Here's the fork [https://github.com/klabhub/matlab-ssh2 ](https://github.com/klabhub/matlab-ssh2 ). I use this primarily inside a different Matlab toolbox to communicate with a SLURM server over SSH ([https://github.com/klabhub/mslurm](https://github.com/klabhub/mslurm)).
